In [1]:
import numpy as np #np is alias

In [2]:
my_list = [1, 2, 3, 4, 5]
# Multiplying each item by 3
result_list = []
for item in my_list :
    result_list . append ( item * 3)



# Python (manual matrix multiplication)
def matrix_multiply (a, b):
    result = []
    for i in range ( len (a)):
        row = []
        for j in range ( len (b [0]) ):
            total = 0
            for k in range ( len (b)):
                total += a[i][k] * b[k][j]
            row.append ( total )
        result.append (row )
    return result

# Example matrices: (2x3) * (3x2) -> (2x2)
A = [
    [1, 2, 3],
    [4, 5, 6],
]
B = [
    [5,  8],
    [9, 10],
    [11, 13],
]

C = matrix_multiply(A, B)

# Print the outcome
print("Product A x B:")
for r in C:
    print(r)

Product A x B:
[56, 67]
[131, 160]


In [4]:
#Code with numpy
def matrix_multiply_np (a, b):
    return np. dot (a, b)

C = matrix_multiply(A, B)

# Print the outcome
print("Product A x B:")
for r in C:
    print(r)

Product A x B:
[56, 67]
[131, 160]


In [5]:
#Creating arrays
arr1 = np.array([1, 2, 3, 4, 5]) #1-D arrays
arr2 = np.array([[1, 2, 3], [4, 5, 6]]) #2-D arrays (like tables)
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) #3-D Arrays
arr_n = np.array([1, 2, 3, 4], ndmin=9) #high-dimensional array


In [6]:
#Printing the arrays created above
print("1-D Array Example:",arr1)
print("2-D Array Example:",arr2)
print("3-D Array Example:",arr3)
print("9-D Array Example:",arr_n)

1-D Array Example: [1 2 3 4 5]
2-D Array Example: [[1 2 3]
 [4 5 6]]
3-D Array Example: [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
9-D Array Example: [[[[[[[[[1 2 3 4]]]]]]]]]


In [9]:
#Sorting arrays
arr1 = np.array([5, 3, 2, 0, 1])
print("Sorted arr1:",np.sort(arr1))

arr2 = np.array(['banana', 'cherry', 'apple'])
print("Sorted arr2:",np.sort(arr2)) 

arr3 = np.array([[3, 2, 4], [5, 0, 1]])
print("Sorted arr3:",np.sort(arr3))


print("Sorted arr3 by column:", np.sort(arr3, axis = 0))

Sorted arr1: [0 1 2 3 5]
Sorted arr2: ['apple' 'banana' 'cherry']
Sorted arr3: [[2 3 4]
 [0 1 5]]
Sorted arr3 by column: [[3 0 1]
 [5 2 4]]


In [21]:
# Calculate and print EOQ
D = 1200
S = 100
H = 2

EOQ = np.sqrt((2*D*S)/2)
print(f" EOQ is {EOQ.round(2)}")

 EOQ is $ 346.41


In [20]:
# Calculate and print Total Cost
total_cost = (D/EOQ)*(S)+(EOQ/2)*(H)
print(f"Total Cost is $ {total_cost.round(2)}")

Total Cost is $ 692.82


Product A x B:
[56, 67]
[131, 160]


Product A x B:
[56, 67]
[131, 160]
